name: "CI: Android release build with signing"

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  android-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Pub get
        run: flutter pub get

      - name: Decode keystore
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          mkdir -p android/app
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > android/app/cakecost-release.jks
          ls -la android/app

      - name: Create key.properties
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS:        ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD:     ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          cat > android/key.properties <<EOF
          storeFile=cakecost-release.jks
          storePassword=$ANDROID_KEYSTORE_PASSWORD
          keyAlias=$ANDROID_KEY_ALIAS
          keyPassword=$ANDROID_KEY_PASSWORD
          EOF
          echo "key.properties written."

      - name: Inspect signing files (no secrets)
        run: |
          echo "--- key.properties (redacted) ---"
          grep -vE 'Password|Alias' android/key.properties || true
          echo "--- android/app listing ---"
          ls -la android/app

      - name: Build release APK
        run: flutter build apk --release

      - name: Build release AAB
        run: flutter build appbundle --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
