name: Flutter CI

on:
  push:
  pull_request:

jobs:
  android-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Java 17 нужен современному Android Gradle Plugin
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      # Без этой либы сборка Android на Ubuntu часто падает
      - name: Install GLU (build deps)
        run: sudo apt-get update && sudo apt-get install -y libglu1-mesa

      # Принять лицензии Android SDK (иногда без этого Gradle ругается)
      - name: Accept Android licenses
        shell: bash
        run: |
          yes | "${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager" --licenses || true

      - name: Pub get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Build debug APK
        run: flutter build apk --debug --no-shrink

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
